on: [pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: kevincobain2000/action-gobrew@v1
        with:
          version: ${{ matrix.go-version }}

      - name: Gobrew version
        run: gobrew version
      - name: Go version
        run: go version
      - name: Build
        run: go build cmd/gobrew/main.go
