on:
  pull_request:
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'

name: "Build"
jobs:
  build:
    strategy:
      matrix:
        go-version: [latest, dev-latest, mod]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Go version
        run: go version
        shell: bash
      - name: Build
        run: go build cmd/gobrew
        shell: bash
