on: [push, pull_request]
name: CoverItUp
jobs:
  CoverItUp:
    strategy:
      matrix:
        go-version: [dev-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}
      - name: Test
        run: go test -race -v ./... -count=1 -coverprofile=coverage.out

      - name: Coverage
        run: |
          go tool cover -html=coverage.out -o coverage.html
          gocov convert coverage.out | gocov-xml > coverage.xml
      - name: Build
        run: go build -ldflags '-s -w' -o main cmd/gobrew/main.go

      # Coveritup
      - name: Coveritup
        run: |
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/cover-totalizer/master/install.sh | sh
          echo SCORE=`./cover-totalizer coverage.xml` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: coverage

      - name: Go Binary Size
        run: |
          echo SCORE=`du -sk main | awk '{print $1}'` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: go-binary-size

      - name: Number of dependencies
        run: |
          echo SCORE=`go list -m all|wc -l|awk '{$1=$1};1'` >> "$GITHUB_ENV"

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: go-mod-dependencies

      - uses: kevincobain2000/action-coveritup@v1
        with:
          pr_comment: true
